version: "3.1"
services:
    laravel-app:
        build:
            context: "."
            args:
                uid: ${UID}
        container_name: laravel-app
        ports:
            - ${HOST_PORT}:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - .:/var/www/html
        networks:
            backend:
                aliases:
                    - app
    db:
        image: mysql
        container_name: dbmysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: erronka
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - network_test
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - network_test
volumes:
    persistent:
networks: 
    network_test:
